package dev.pdp

enum class ErrorCodes(val code: Long){
    USER_ALREADY_EXISTS(403),
    USER_NOT_FOUND(404),
    CATEGORY_ALREADY_EXISTS(301),
    CATEGORY_NOT_FOUND(302),
    PRODUCT_ALREADY_EXISTS(100),
    PRODUCT_NOT_FOUND(101),
    USER_PAYMENT_ALREADY_EXISTS(102),
    USER_PAYMENT_NOT_FOUND(103),
    TRANSACTION_ALREADY_EXISTS(104),
    TRANSACTION_NOT_FOUND(105),
    TRANSACTION_ITEM_ALREADY_EXISTS(400),
    TRANSACTION_ITEM_NOT_FOUND(401),
}

